imports:
    - { resource: parameters.yaml }
    - { resource: security.yaml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    # knp_menu.voter.router.class: Knp\Menu\Matcher\Voter\RegexVoter
    
framework:
    secret: '%kernel.secret%'
    # knp_paginator needs translate bundle
    translator:
        fallbacks: ['%locale%']
        logging: false
    session:
        # storage_id: session.storage.php_bridge
        handler_id: ~
        name: dome
    fragments:
        path: /_fragment
        hinclude_default_template: hinclude.html.twig # see https://symfony.com/blog/new-in-symfony-4-3-deprecated-the-templating-component-integration

    # Symfony 4.3 adds automatic search-engine protection in debug-mode
    # You can override, see https://symfony.com/blog/new-in-symfony-4-3-automatic-search-engine-protection
    disallow_search_engine_index: false
    router:
        utf8: true

twig:
    globals:
        siteName: "Database of Modern Exhibitions (DoME) | European Paintings and Drawings 1905-1915"
        slugify: "@cocur_slugify"
        webDir: "%kernel.project_dir%/web"
        gaTracking: '%ga.site_id%'
    paths:
        '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates': KnpPaginator
        '%kernel.project_dir%/templates': __main__
    form_themes:
        - '@SpiriitFormFilter/Form/form_div_layout.html.twig'
        - '@TetranzSelect2Entity/Form/fields.html.twig'
    #form:
    #    resources: ['bootstrap_3_horizontal_layout.html.twig']
    exception_controller: null
    strict_variables: false     # TODO: make safe for '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                host:     '%database.host%'
                port:     '%database.port%'
                dbname:   '%database.name%'
                user:     '%database.user%'
                password: '%database.password%'
                #driver:  pdo_mysql
                charset:  '%database.charset%' # UTF8
                options:
                        1002: "SET NAMES '%database.charset%' COLLATE '%database.charset%_unicode_ci'"
                default_table_options:
                    charset: '%database.charset%'
                    collate: '%database.charset%_unicode_ci'
                    engine:  MyISAM     # InnoDB
    orm:
        connection: default        
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true
        dql:
            string_functions:
                FIELD: DoctrineExtensions\Query\Mysql\Field
                IF: DoctrineExtensions\Query\Mysql\IfElse
                REPLACE: DoctrineExtensions\Query\Mysql\Replace
                REGEXP: DoctrineExtensions\Query\Mysql\Regexp
                JSON_CONTAINS: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains
            numeric_functions:
                MATCH: DoctrineExtensions\Query\Mysql\MatchAgainst
                RAND: DoctrineExtensions\Query\Mysql\Rand
            datetime_functions:
                YEAR: DoctrineExtensions\Query\Mysql\Year
                
        #result_cache_driver: '%database.cache_driver%'
        #query_cache_driver: '%database.cache_driver%'
        result_cache_driver: ~
        query_cache_driver: ~
        second_level_cache:
            enabled: false

#doctrine_cache:
#    providers:
#        vendor_filesystem_metadata_cache:
#            file_system:
#                extension: cache
#                directory: '%kernel.cache_dir%/doctrine'
#        vendor_filesystem_result_cache:
#            file_system:
#                extension: cache
#                directory: '%kernel.cache_dir%/doctrine'
#        vendor_filesystem_query_cache:
#            file_system:
#                extension: cache
#                directory: '%kernel.cache_dir%/doctrine'
            
stof_doctrine_extensions:
    orm:
        default:
            timestampable: true

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: KnpMenuBundle::menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig


scssphp:
    assets:
        "css/base.css":
            src: "web/assets/scss/base.scss"
            sourceMap: true
            outputFolder: web
#            importPaths:
#                - "vendor/twbs/bootstrap/scss"
#            variables:
#                primary: '#ff0066'

liip_url_auto_converter:
    linkclass:
    target: _blank
    debugmode: false

knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query paameter name
    template:
        # pagination: 'KnpPaginatorBundle:Pagination:sliding.html.twig'     # sliding pagination controls template
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v3_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template

swiftmailer:
    # disable_delivery:  true
    # delivery_address: daniel.burckhardt@sur-gmbh.ch
    # or use: delivery_whitelist
    transport: '%mailer.transport%'
    host: '%mailer.host%'
    port: '%mailer.port%'
    username: '%mailer.username%'
    password: '%mailer.password%'
    encryption: ssl
    # self-signed, see https://github.com/swiftmailer/swiftmailer/issues/544
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false

#debug:
#    dump_destination: "tcp://%env(VAR_DUMPER_SERVER)%"
