imports:
    - { resource: config.yaml }

framework:
    profiler:
        enabled: false # true by default
        only_exceptions: false

monolog:
    handlers:
#        console:
#            type:   console
#            verbosity_levels:
#                VERBOSITY_NORMAL: NOTICE # DEBUG
#        stream:
#            type: stream
#            # log to var/logs/(dev|prod).log
#            path: "%kernel.logs_dir%/%kernel.environment%.log"
#            level: error
