# Explicitly state the followin in order for *-index in SearchController to take precedence over detail routes
SearchController:
    resource: '@AppBundle/Controller/SearchController.php'
    type: annotation

ExhibitionController:
    # this one must go after SearchController
    resource: '@AppBundle/Controller/ExhibitionController.php'
    type: annotation
    
PersonController:
    # this one must go after SearchController
    resource: '@AppBundle/Controller/PersonController.php'
    type: annotation
    
LocationController:
    # this one must go after SearchController
    resource: '@AppBundle/Controller/LocationController.php'
    type: annotation
    
HolderController:
    # this one must go after SearchController
    resource: '@AppBundle/Controller/HolderController.php'
    type: annotation
