# config/security.yaml

# see https://symfony.com/doc/5.3/security.html
security:
    enable_authenticator_manager: true

    password_hashers:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            provider: db_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
        
    access_control:
        - { path: ^/work, roles: ROLE_USER }
        - { path: ^/my-data, roles: ROLE_USER }
        - { path: ^/(exhibition|person|location|organizer|holder|search)/save, roles: ROLE_USER }
        # everything else is free
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

