# config/security.yaml

# see https://symfony.com/doc/3.4/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            anonymous: ~
            provider: db_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
        
    access_control:
        - { path: ^/work, roles: ROLE_USER }
        # everything else is free
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
