# config/services.yaml
services:
    twig.extension.text:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
    app.menu_builder:
        class: AppBundle\Menu\Builder
        arguments: ["@knp_menu.factory", "@request_stack"]
        tags:
            - { name: knp_menu.menu_builder, method: createTopMenu, alias: top } # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: createFooterMainMenu, alias: footer-main } # The alias is what is used to retrieve the menu
